# Generated by Django 5.2.8 on 2025-11-18 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=15, unique=True)),
                ('tipo_aeronave', models.CharField(max_length=50)),
                ('capacidad_kg', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('licencia', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('certificacion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_transporte', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('AEREO', 'Aéreo')], default='TERRESTRE', max_length=15)),
                ('distancia_km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('capacidad_kg', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('peso_kg', models.FloatField()),
                ('tipo_mercancia', models.CharField(max_length=50)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='transporte.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20)),
                ('costo_envio', models.FloatField()),
                ('aeronave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='transporte.aeronave')),
                ('carga', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despacho', to='transporte.carga')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='transporte.conductor')),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='transporte.piloto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='transporte.ruta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='transporte.vehiculo')),
            ],
        ),
    ]
